travis:
  secure:
    BINSTAR_TOKEN: InKIwEaGRLhgSVqoP1TUWXf56VI+MHgRdUhm6XXvrwgvvzaFqQcGrs9r3X5d7XlwjwuevDWq90vrnMXbLQDFVpxYvuWuzuSceVFAxbPvcYrb50hT+DwX+aspDOrC+e9nonF0uvL0pakdjNEOAVGew4rZUaGUbBExbK4OiuNanImA8Cn/jxbRYZdkMtzTI6hcqrol4qqQiSJXG5nNlEZ/3SaRsKOlh4z026aYzGn+EUQOCzvc/cfrf1jglUXF2rJ2NldMRVN2EQ2UYqbi+xQhUPq3Ml0Opyii+YQnNa9MihfUCRugOdD6hQ+gjQoHlvI195+9ti+9X1AKYdIAVj6lTdfUOukdaJDwRln99kKheZhOAqPrBtZ46ELQ2aXv9FRsmrg0cUkBJHVFXLtPNFwNqEvA8eSEMizz1nSCBQ7HnsECqemGAHX20UdPIIrLNqQSM+BP2Ko58yQ6TkyifRoj49v2cdxfOeyw3y74yn5PpnHtFTrzdqMZ7aTQJmAMzNHI8+kdj6BSi/QCPYV+hoQfsRIb8Ik7s6TMh8eWUnoz/j1rL3E7FdaPz/gkqZz6/idvhbPUqnsvZfGHMNQN81gw9YY4E8RKFTfAdll9qJxMUYLLO/jdC+pnmfDzcWLQO2tPGmV5ytY9n8DqmUnVdP+XGADHJzdgZx2V7WHbQoJjPOY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
