travis:
  secure:
    BINSTAR_TOKEN: d0mC7UZItootW+MiuyfwJPMA36hMxnb7YuhUPP8GFMf1SNVA4kmaJupWuqexLtOP3By2GqQs9/5VRxvufIwgcoOsYkkavZjbi6Ik7PVeXIxIjzaVpPJZdPMwTf5M6Tp8vWuMAtAS+9wykQW9saP/Ld2jqQ9RSs5NsLhJRKI7HChBfq2UcIBe0x/NCoprWxQrcuc+bvDL4dWwhsU1gEPirhutKsbIEpPxrN8ixYI9TOcX63eTizYjrp/9PjJfE/D6BeBZHLpuffUVBt+fS8+H1DGKwl9YqSz5dZNS6IvBBWjy7GCRoYk5PFVTZ5Y+K9yvNmXqLNrDfd36QT20YWpdhmvNkLXxaP09rnzQCm07nChvPIB7Je1xVxtdPzwRsU+i0DEIJ2CNfP4g0yEUXNc576+xNUDViz3Q2NZdEKQYWg/QF9IJduuiuoUd4jQybbTdzhzGwVogeYtAIjzkZ7Kx6ZnEfK7M77ClxVJWiCZQ05zQoZ35t7bkw/CtZEEwr8+DbHiYtn3HpRm+eWRXMDogf0yvnbquHu64WZyTrOHfobtJ7VvwJXc7bPF5Z6p3q8t8A0opBJB+aXtxxH5O547XpAfp+gsY5xbYI23pgh3is9Ry4yuGgiBw5ds3JEoEFgkH4wbs0Zfy/m7AUtxZO14Sh30abmhF6KGAQ+GqhVEJJeo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
