travis:
  secure:
    BINSTAR_TOKEN: FQ+LQjH/FV/uTall9qENlwMI0F+ZRYkyiEzYbzn4slIRMzCbcpbBpizR7ir2Z3j9lOjTDATd7bCQkhqLuwL2vfQ8v23L/fOlaSu4PwU5OQPuQ9NJjKeMvVtoQ2AGybWBohgc7pT9I8mSh4TMRH0na90yItrNvf6YJNMdgRGxvJH9Pq5ijNOVA1C6GEJKez5XezG27mZJt0yLyfopt4iJpLBdbbVwZD/Lc033f10U8YJjrWmkN9NUpPi7DU6D5K1E5R10LlD7QLGBrJdCPcXAIfL/DVLQN8/pguQ6OLeCCZzCr6SMuMbY7FF1RvJdntaWTPz3Q8+7l9/H2+C6eZGEyUsY3wLQACbqiOsxNxzrnlVpz7SwTcPkZaVLcmA7vO5CJA27YDVPDMtU5yX89CISHfiOo+LDDpi5U7zzXMQqgd0EvlUbBlU2dpyCS1zaQ0XS2AQJeFvWeYuoPHL5m6XxdKN9nEdXdQvn33ZHjcGXdNj5kNI/RxJe8Ozb+0poCXvXSW6OmSCysBASB0hDIHJ9/6abuEf9X5NPqJlY4lcQrTmlmENqeKqXk2hgpWY49EA4XpOZ3jflouiHQeIAYOytw280fun6zudDoYxs5xDniF7LtZDXT7MGzy6cUghQUV7wBCWGrbHebnpRijiUiGOOVNL/KKF85hCpjFJgFLdb4p8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
