appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qKI0eEl37NRVZWE0zLg+NKiJRNJvIo0gwBidVcfia7g7U7vZin49P90KxqWJduDreAsFr4b/WXDxuJ/xYiETJxIt03flmAEVnpGww4HzwSKAdclQQXf0tDteoyL1gEo9WxYl4vHK5AQnod4grMhluWBH6tQrvklnUmzbz/XK3h6VjMxKEk8goi3f/k881CVjDOLYTACbKkVCt+9MJ7Ju88qbgAEJnsnQZ1JjD02tIARUh7bJEzGljimbDKAXc6bsJ64fqFhf5MgIpCzB9+mWR9+WUwNJtNTaacelse1vxvfJwrZiSWJqxFGODbvbNoZ2aZBWXXGOMa1np0AGOyhD4qqekuG2zrYSDxSsggrZsChaVwT9cuY62C6cSQcoqLtgQl9T5g3agK99IxkUfGsfZp/nBMniKZdANFCPpPpC0WyxldnY7NNpQ65fhZVl2kgQ3lMnhd0KlQf4DJBJIMpt2srOxdBZTR4+9ocOysHsmBcWtt7DWpJoNsL17W0r3gUjnorQsMu5tVfUQIKEkVnstDJ4ub4nwcfwfMCnDaV4/jhmwRESEkINp2ZSubjJZsRVIFo/aGF/sswuYOBtqKw9umWTOTwhW12Yqb7AQUOA0ELxggCsV4fVlxWmWbuyFObDrKR6kdyc8hC6rWo6B2ollCRQrA3mjObtydP8tygNGJs=}
